In [5]:
import pandas as pd

In [6]:
df_leads = pd.read_csv("2023-08-17-Day91Leads.csv")
df_leads_old = pd.read_csv("20230815-Day91Leads.csv")

In [8]:
df_leads = df_leads.sort_values(by=["nk_dotnbr"])
df_leads_old = df_leads_old.sort_values(by=["nk_dotnbr"])

In [9]:
df_leads.eq(df_leads_old)

,nk_dotnbr,stc_sf_id,stc_contact_id,open_cs_opp_id,cs_opp_last_activity,cs_opp_owner,stc_sf_name,pfj_sf_name,state,pfj_contact_first_name,...,rm_rate,last_nsf_date,rep,bucket,repid,Contact Attempted,Lead Status,Campaign,Topic of Interest,Lead Record Type
389,True,False,False,False,False,False,False,True,True,True,...,True,False,False,True,False,True,True,True,True,True
373,True,False,False,False,False,False,False,True,True,True,...,True,False,True,True,True,True,True,True,True,True
110,True,False,False,False,False,False,False,True,True,True,...,False,False,False,True,False,True,True,True,True,True
263,True,False,False,False,False,False,False,True,True,True,...,True,False,False,True,False,True,True,True,True,True
46,True,False,False,False,False,False,False,True,True,True,...,True,False,False,True,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,True,False,False,False,False,False,False,True,True,True,...,True,False,True,True,True,True,True,True,True,True
697,True,False,False,False,False,False,False,True,True,True,...,True,False,False,True,False,True,True,True,True,True
541,True,False,False,False,False,False,False,True,True,True,...,True,False,False,True,False,True,True,True,True,True
190,True,False,False,False,False,False,False,True,True,True,...,True,False,False,True,False,True,True,True,True,True
136,True,False,False,False,False,False,False,True,True,True,...,True,False,False,True,False,True,True,True,True,True

In [10]:
df_newopps = pd.read_csv("2023-08-17-Day91NewOpps.csv")
df_newopps_old = pd.read_csv("20230815-Day91NewOpps.csv")

In [11]:
df_newopps = df_newopps.sort_values(by=["nk_dotnbr"])
df_newopps_old = df_newopps.sort_values(by=["nk_dotnbr"])

In [12]:
df_newopps.eq(df_newopps_old)

,nk_dotnbr,stc_sf_id,stc_contact_id,open_cs_opp_id,cs_opp_last_activity,cs_opp_owner,stc_sf_name,pfj_sf_name,state,pfj_contact_first_name,...,rm_rate,last_nsf_date,rep,bucket,repid,Close Date,Primary Source Campaign ID,Opportunity Type,RecordTypeId,StageName
60,True,True,True,False,False,False,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
67,True,True,True,False,False,False,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
129,True,True,True,False,False,False,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
88,True,True,True,False,False,False,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
86,True,True,True,False,False,False,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,True,True,True,False,False,False,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
10,True,True,True,False,False,False,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
123,True,True,True,False,False,False,True,True,True,False,...,True,False,True,True,True,True,True,True,True,True
49,True,True,True,False,False,False,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
27,True,True,True,False,False,False,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True